### PR TITLE
cmdstanr benchmarking

### LINKED ISSUE #391: Add in model profiling via touchstone
We could include the in model profiling as a `touchstone` benchmark. Would have to do it running key functions from R which is a pain vs the integrated cmdstanr profiling but still might be useful

_Originally posted by @seabbs in https://github.com/epiforecasts/EpiNow2/issues/363#issuecomment-1543834388_

### PR DESCRIPTION
**Pull request by sbfnk**
## Description

If it works (and I don't know if it will) then this PR closes #391.

It doesn't use touchstone (as I couldn't see how this might be integrated) but a custom action and the scripts from #415.

## Initial submission checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have tested my changes locally (using `devtools::test()` and `devtools::check()`).
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required and rebuilt docs if yes (using `devtools::document()`).
- [X] I have followed the established coding standards (and checked using `lintr::lint_package()`).
- [x] I have added a news item linked to this PR.

## After the initial Pull Request 

- [ ] I have reviewed Checks for this PR and addressed any issues as far as I am able.

### CODE REVIEW

**Comment by sbfnk** [comment]
There might be some tweaking to do but in principle this works now. We might just replace touchstone with this as it's proven a bit unwieldy and we really care about performance of the stan model, not so much of the R code.

@seabbs might be of interest for epinowcast, too.

**Review by jamesmbaazam — APPROVED** [review]
This is super! I've gone through it and not seen any issues.

**Comment by sbfnk** [comment]
> This is super! I've gone through it and not seen any issues.
> 
> Could we provide a textual interpretation of the CIs as a column (for example, "slower"/"faster"), similar to touchstone?

I've added this, see latest benchmarking comment.

**Review by jamesmbaazam — DISMISSED** [review]

**Comment by seabbs** [comment]
This is really lovely and agree good to merge. IMO it complements vs replaces touchstone as it doesn't test whole workflows and it doesn't test a fair few model permutations (I believe). 

_This would be a good candidate for making into a generic action others can use I think with a bit of tooling around it to do the benchmarking. I'd like it for `epinowcast` for example._

**Comment by seabbs** [comment]
Ah one actual comment. Maybe we want to only print a comment if a benchmark has changed in order to reduce PR noise or trigger on a / command?

**Comment by sbfnk** [comment]
> Ah one actual comment. Maybe we want to only print a comment if a benchmark has changed in order to reduce PR noise or trigger on a / command?

done (and seems to work)

**Comment by sbfnk** [comment]
> _This would be a good candidate for making into a generic action others can use I think with a bit of tooling around it to do the benchmarking. I'd like it for `epinowcast` for example._

I agree

**Pull request merged**
