### PR TITLE
reduce alpha prior sd again

### PR DESCRIPTION
**Pull request by sbfnk**
Suggesting to revert the recent change in the prior sd of alpha (https://github.com/epiforecasts/EpiNow2/pull/840) in the light of the issues seen in https://github.com/epiforecasts/EpiNow2/pull/847 and the exploration in https://github.com/epiforecasts/EpiNow2/pull/855.

### CODE REVIEW

**Comment by sbfnk** [comment]
This will re-open the issue in https://github.com/epiverse-trace/howto/issues/81 which will have to (and can) be addressed in some other way.

**Comment by jamesmbaazam** [comment]
> This will re-open the issue in [epiverse-trace/howto#81](https://github.com/epiverse-trace/howto/issues/81) which will have to (and can) be addressed in some other way.

Isn't the solution to use the prior in the previous version? In the how-to, the concern is not about divergences but how to set up a model.

**Review by jamesmbaazam — APPROVED** [review]
LGTM.

**Comment by sbfnk** [comment]
> > This will re-open the issue in [epiverse-trace/howto#81](https://github.com/epiverse-trace/howto/issues/81) which will have to (and can) be addressed in some other way.
> 
> Isn't the solution to use the prior in the previous version? In the how-to, the concern is not about divergences but how to set up a model.

The solution is indeed to either use `prior = "infections"` or manually set `alpha_sd` in the howto.

**Pull request merged**
