### PR TITLE
do not merge -- try to fix failing R CMD CHECK

### PR DESCRIPTION
**Pull request by sbfnk**
by stabbing in the dark

### CODE REVIEW

**Comment by sbfnk** [comment]
It seems to be the [R commands](https://github.com/epiforecasts/EpiNow2/blob/048c71d61cb241dfab137c374451edc024db168b/configure#L7) in the `configure` file that break this - specifically `src/Makevars.win` not being found which to me is a complete enigma because it would imply that `src/Makevars` is found.

@seabbs did this solution come from somewhere else? And given that this is a shell script already, is there any reason not to do the editing of `Makeavars` using shell commands here in a random attempt to fix this?

**Comment by seabbs** [comment]
So it came from a thread on the CRAN requirements change. It looks like however that this could be cause by the `rstantools` update which should have fixed the original issue (and now looks to be on CRAN)

**Comment by seabbs** [comment]
well damn - that didn't fix it.

**Comment by sbfnk** [comment]
Closing as all seems fine now (🤞).

**Pull request closed without merging**
