### PR TITLE
Update and reorganize GitHub Actions (GHA) workflows

### PR DESCRIPTION
**Pull request by hsbadr**
This PR updates GHA workflows and fixes `R CMD check`:

- [X] Lint all GHA workflows using `yamllint`
- [X] Upgraded Linux runner to `ubuntu-20.04`
- [X] Update and use GHA releases
- [X] Explicitly specify bash shell
- [X] Convert Lint & Format workflows to sequential jobs
- [X] Format job pushed changes to PR, if needed, after successful checks
- [X] Always Lint and Format after successful checks
- [X] Deploy website after code formatting, test coverage, and successful checks
- [X] Build Docker image after checks, test coverage, and `pkgdown`
- [X] Limit some jobs on `master` branch and skip forks
- [X] Enable manual trigger of full checks
- [X] Clean up PR Commands workflow
- [X] Let R-CMD-check workflow fail fast
- [X] Fix Lint and Format steps and run them in parallel
- [X] Install the required system dependencies
- [X] Explicitly install `EpiSoon` from GitHub to fix `R CMD check`

Here's a screenshot of the current workflow (and [here](https://github.com/hsbadr/EpiNow2/actions/runs/491154571)):
EpiNow2_GHA_workflow

### CODE REVIEW

**Comment by hsbadr** [comment]
@seabbs All checks are successful: https://github.com/hsbadr/EpiNow2/actions/runs/491154571. I'm not sure why this fails here. I'll check the log files tomorrow.

**Comment by seabbs** [comment]
Thanks for this @hsbadr  - very nice. Flow chart of jobs is great, not something I was aware you could do. I only just noticed (no internet this weekend that the check has been failing due to `EpiSoon` (hope to cut that dependency asap) - odd that has just started happening. 

Not clear to me what the issue is with this here vs in your repo. Trying a rerun to see if that changes anything. 

In general, I am less clear that formatting the stan generated C++ code makes sense as every time stan regenerates it it obviously gets overwritten causing a whole lot of PR noise. Unless you are very strongly for it I would probably go with cutting that section. 

Nice work on your `bayesian` package by the way!

**Comment by hsbadr** [comment]
> Thanks for this @hsbadr - very nice. Flow chart of jobs is great, not something I was aware you could do. I only just noticed (no internet this weekend that the check has been failing due to `EpiSoon` (hope to cut that dependency asap)) - odd that has just started happening.
> 
> Not clear to me what the issue is with this here vs in your repo. Trying a rerun to see if that changes anything.
> 
> In general, I am less clear that formatting the stan generated C++ code makes sense as every time stan regenerates it it obviously gets overwritten causing a whole lot of PR noise. Unless you are very strongly for it I would probably go with cutting that section.
> 
> Nice work on your `bayesian` package by the way!

Thanks @seabbs ! I've fixed `EpiSoon` dependency in this PR by installing it from GitHub. I see your point about the formatting; we can disable the commit step with a condition, in case we need it later.

**Comment by hsbadr** [comment]
@seabbs Now, you need to start a commit message with `[format]` to run the formatting job if needed; otherwise, it will get skipped.

**Comment by seabbs** [comment]
Excellent!

**Comment by hsbadr** [comment]
It's still failing here, but not for me: https://github.com/hsbadr/EpiNow2/actions/runs/494155559

**Comment by hsbadr** [comment]
@seabbs The checks are successful here finally 💥

**Comment by seabbs** [comment]
Well done. How bizarre that this only occurred here and not in the fork though. Thanks again for this - very nice to have.

**Comment by hsbadr** [comment]
@seabbs Need to check if you're satisfied with the condition for the docker and `pkgdown`:
https://github.com/epiforecasts/EpiNow2/blob/590f3807d7896f4cf70617120b58adc03f7c5428/.github/workflows/check-full.yaml#L295

You may want to change it if you don't push to `master` and always do PRs.

**Comment by hsbadr** [comment]
> How bizarre that this only occurred here and not in the fork though.

I think this is due to caching R packages, which has been been cleared when I upgraded the runners. You may change the number in the `key` (e.g., `-1-` to `-2-`) to clear the cache if you run into similar issues. This will slow your first new run though.

https://github.com/epiforecasts/EpiNow2/blob/590f3807d7896f4cf70617120b58adc03f7c5428/.github/workflows/check-full.yaml#L54-L60

**Comment by seabbs** [comment]
Ah that sounds likely. Thanks - good tip.

**Comment by hsbadr** [comment]
> In general, I am less clear that formatting the stan generated C++ code makes sense as every time stan regenerates it it obviously gets overwritten causing a whole lot of PR noise. Unless you are very strongly for it I would probably go with cutting that section.

We could enable the auto formatting job and use this [`configure`](https://github.com/hsbadr/EpiNow2/blob/develop/configure) to regenerate formatted code.

**Pull request merged**
