### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by seabbs**
Adds new linters, adds a changed file only listing action, deals with linting issues across the package (aside from nested `ifelse` - making a help wanted issue), adds an action for rendering the README, cleans up install instructions, goes quietly mad in a corner.

### CODE REVIEW

**Comment by sbfnk** [comment]
This is going to mess with ongoing deveopment in open PRs (especially #363) - might be worth waiting for that and then running the linter?

**Comment by sbfnk** [comment]
> I did this manually. I am happy to deal with merge issues (also manually) what a dream.

Ah it's fine I'll manage I'm sure. Just might involve some cursing.

> I think we need to get the code base in a nice clean place to enable rapid iteration. Having good linting etc will help avoid building in more technical debt. Especially if others are going to make contributions.

Completely agree.

**Review by sbfnk — APPROVED** [review]

**Comment by seabbs** [comment]
okay I was not expecting the merge queue to do that...

**Comment by seabbs** [comment]
I assumed it would wait for checks 😭

**Comment by Bisaloo** [comment]
> This is how benchmark results would change (along with a 95% confidence interval in relative change) if [9bc622a](https://github.com/epiforecasts/EpiNow2/commit/9bc622ab8af797ec30029d51b1f53a32e135b654) is merged into main:
> 
>     * exclamationsnaildefault: 53s -> 5.57m [+457.36%, +603.41%]
> 
>     * exclamationsnailno_delays: 44.6s -> 4.5m [+432.73%, +577.94%]
> 
>     * exclamationsnailrandom_walk: 15.6s -> 30.1s [+75.09%, +112.32%]
> 
>     * exclamationsnailstationary: 37.2s -> 3.71m [+357.31%, +640.01%]
> 
>     * exclamationsnailuncertain: 55s -> 5.74m [+392.33%, +661.5%]
>       Further explanation regarding interpretation and methodology can be found in the [documentation](https://lorenzwalthert.github.io/touchstone/articles/inference.html).

This is likely not correct and just due to the update to R 4.3.0 and the fact that the entire package cache needed to be rebuilt.

**Pull request merged**
