### PR TITLE
1.3.5 minor release

### PR DESCRIPTION
**Pull request by seabbs**
This is a minor release to deal with compilation issues on CRAN. Currently testing on `rhub`.

### CODE REVIEW

**Comment by seabbs** [comment]
@sbfnk any idea why touchstone is failing now? I see some minor differences between main and develop for the touchstone configuration with I think those on develop being the more recent?

**Comment by seabbs** [comment]
😱

**Review by sbfnk — APPROVED** [review]
checks, rhub, windevel and touchstone all look fine now - time to get back to CRAN?

**Comment by seabbs** [comment]
`rstan` is in the middle of being updated on CRAN and it sounds like they expect it to be soon. Perhaps we should wait for this?

**Comment by sbfnk** [comment]
I think we should go ahead now - who knows how long they'll take.

**Comment by seabbs** [comment]
> I think we should go ahead now - who knows how long they'll take.

This has happened it seems. It looks like they now support `2.26`. This might mean they are on the pathway to being up to date.

**Comment by sbfnk** [comment]
Exciting!!

**Pull request merged**
