### PR TITLE
Error handling simulate_infections

### PR DESCRIPTION
**Pull request by nikosbosse**
this PR
- updates the example in the documentation
- adds some error handling if the wrong dimensions for new R values are passed into the function

### CODE REVIEW

**Comment by nikosbosse** [comment]
not sure that was along the lines of what you thought of. Happy to update if you have feedback :)

**Review by seabbs — COMMENTED** [review]
Can you clarify why the tests are failing and if that is expected please (sorry this took a while to get back to you about).

**Comment by seabbs** [comment]
Ping. Any progress with this?

**Comment by seabbs** [comment]
AH right yes that doesn't sound ideal. I have no real idea what this was trying to fix either.... so perhaps shall we close and chalk it up to lessons learned?

**Comment by nikosbosse** [comment]
Could alternatively change it to make sure the Rt passed in isn't *shorter* than the original one, but allow for *longer* ones? 
Happy to shelf though :)

**Pull request closed without merging**
