### PR TITLE
Discretise with two-day censoring windows

### LINKED ISSUE #411: Discretisation
The current discretisation of delay distributions integrates between integer boundaries [0, 1], [1, 2], ...

Recent work has shown that this leads to bias. A better option would be to discretise as [0, 1], [0, 2], [1, 3], ...

### PR DESCRIPTION
**Pull request by sbfnk**
This has been shown to reduce bias in the discretisation. More detail in https://package.epinowcast.org/dev/articles/distributions.html

Closes #411

### CODE REVIEW

**Comment by sbfnk** [comment]
Some delay-related tests failing - will revisit after merging #504

**Review by jamesmbaazam — APPROVED** [review]
I've crosschecked this against [the epinowcast vignette on discredited delays](https://package.epinowcast.org/dev/articles/distributions.html#discretisation-and-adjustment-for-maximum-delay) and it looks good to me.

**Comment by sbfnk** [comment]
> I've crosschecked this against [the epinowcast vignette on discretised delays](https://package.epinowcast.org/dev/articles/distributions.html#discretisation-and-adjustment-for-maximum-delay) and it looks good to me.

Thanks! Added you as a reviewer - if happy please re-approve.

**Review by jamesmbaazam — APPROVED** [review]

**Review by seabbs — COMMENTED** [review]
Sorry i haven't had a chance to fully review but the stan code looks in line with what I expect. Happy to see this merged once @jamesmbaazam is happy (I think we want a big news note about this at the least though as it will change what people are getting).

I think this is true but also we should double check that the R side discretisation implementation is either the same approximation or the more accurate simulation base approach epinowcast uses. 

Note both of these should be replaced soon with and at least R side standalone package that handles this all numerically.

**Comment by sbfnk** [comment]
> I think this is true but also we should double check that the R side discretisation implementation is either the same approximation or the more accurate simulation base approach epinowcast uses.

Yes it should be - we're already testing that in https://github.com/epiforecasts/EpiNow2/blob/93c072d9aad839ccda76fa75f74ebc9d403f4d26/tests/testthat/test-dist.R#L4

**Review by jamesmbaazam — APPROVED** [review]
I'm happy for this to be merged.

**Pull request merged**
